### ISSUE TITLE
"Could not identify the Firefox process" despite successfully crashing it

### ISSUE THREAD

**Issue by dholbert** [b0bh00d/crash-firefox#5]
I'm just trying this utility for the first time (hoping to use to help a colleague diagnose a hang).

One thing I noticed: I'm getting a spurious "Could not identify the Firefox process"  warning-dialog, even though CrashFirefox did in fact successfully identify and crash the Firefox process.

STR:
1. Have a single Firefox Nightly window open.
2. Double-click CrashFirefox.exe in your file manager.
3. Accept its automatic selection of firefox PID and click "Zap"

ACTUAL RESULTS:
Firefox crashes (hooray!) and CrashFirefox pops up a confusing message saying "Could not identify the Firefox process!"

EXPECTED RESULTS:
No such dialog.

Maybe this dialog is just reporting that the Firefox process is successfully killed, and now Crash Firefox [still open] can't find any additional Firefox processes?  But I'm not sure, because I still see the same error even if I have multiple Firefox instances open and I only crash one of them.

**Comment by dholbert** [comment]
Here's a screencast showing the bug:

[Screencast from 02-05-2024 04:18:59 PM.webm](https://github.com/b0bh00d/crash-firefox/assets/426803/fb6e9526-55e1-4067-8ea3-6188ccb73108)

**Comment by b0bh00d** [comment]
Please test the current release when you get a chance.

**Comment by b0bh00d** [comment]
Sorry, nvm.  It didn't reproduce the first time I tried it.  Now it does.  I'll have to dig a bit deeper.

**Comment by b0bh00d** [comment]
Ok, try the v1.3 release.  Should be better behaved.

**Comment by dholbert** [comment]
> Sorry, nvm. It didn't reproduce the first time I tried it. Now it does. I'll have to dig a bit deeper.

Yup, it didn't reproduce reliably for me either (should've mentioned), but it was pretty repeatable.

> Ok, try the v1.3 release. Should be better behaved.

I tried it a bit -- haven't hit this issue or any others so far. Thanks!
